### ISSUE TITLE
Instructions to use the session store

### ISSUE THREAD

**Issue by jaimeperez** [feideconnect/simplesamlphp-module-cassandrastore#4]
In the readme, you can read this:

> ## Using the session store
> In config.php
> 
> ```
> 	'session.handler'       => '_',
> ```

What's the relation between the session storage and the metadata storage? Shouldn't those two be completely independent? I understand the module provides a backend for both, but it's not clear from the README.

In any case, what does the `_` mean in the `'session.handler'` option? I believe this won't work at all, as it should be in this case `cassandrastore:CassandraMetadataStore`.

**Comment by andreassolberg** [comment]
Sorry about the smiley '_' 
It was only a placeholder until I found the real proper value to configure the session store.
And yes, session store and metadata store is completely independent. However this module has support for both. Further down in the README it is specified how to use cassandra as the metadata store.

**Comment by jaimeperez** [comment]
😄 

Great! Thanks Andreas! I was a bit confused between the two, and thought they were related somehow...
