### ISSUE TITLE
Use namespaces

### ISSUE THREAD

**Issue by jaimeperez** [feideconnect/simplesamlphp-module-cassandrastore#5]
Nowadays, _namespaces_ are preferred instead of using underscores in long class names. SimpleSAML modules should be in the `SimpleSAML\Module\modulename` namespace, so the two classes defined here should be:

```php
<?php
namespace SimpleSAML\Module\cassandrastore\Store;

class Cassandra extends \SimpleSAML_Store
{
    ...
```

in the `lib/Store/Cassandra.php` file, and

```php
<?php
namespace SimpleSAML\Module\cassandrastore\MetadataStore;

class Cassandra extends \SimpleSAML_Metadata_MetaDataStorageSource
{
    ...
```

in the `lib/MetadataStore/Cassandra.php` file.

I'll also take a look at SSP to make it possible to specify the class name directly, instead of the current _modulename:ClassName_ syntax. That way, implementations won't be restricted to a fixed folder structure, but that will still require some work...

**Comment by andreassolberg** [comment]
Thanks for the tip, @jaimeperez !

**Comment by jaimeperez** [comment]
No prob!

It will work the way it is today too, of course, but we are trying to move to namespaces to make things simpler, so it makes sense to implement it like that from the beginning so that you don't have to migrate later.

By the way! Let me know when you think the module is ready and can be used, so that I can include it in the [list of available modules](https://simplesamlphp.org/modules) 😉

**Comment by andreassolberg** [comment]
Feel free to add to the list of available modules.
